apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.porkbun
  labels:
    app: porkbun
    release: porkbun-v0.0.1
    heritage: porkbun
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/porkbun-webhook-tls"
spec:
  group: porkbun
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: porkbun
    namespace: cert-manager
  version: v1alpha1
