apiVersion: v1
kind: ServiceAccount
metadata:
  name: porkbun
  namespace: cert-manager
  labels:
    app: porkbun
    release: porkbun-v0.0.1
    heritage: porkbun
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porkbun:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: porkbun
    release: porkbun-v0.0.1
    heritage: porkbun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: porkbun
    namespace: cert-manager
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: porkbun:auth-delegator
  labels:
    app: porkbun
    release: porkbun-v0.0.1
    heritage: porkbun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: porkbun
    namespace: cert-manager
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: porkbun:domain-solver
  labels:
    app: porkbun
    release: porkbun-v0.0.1
    heritage: porkbun
rules:
  - apiGroups:
      - porkbun.cert-manager.io
    resources:
      - '*'
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: porkbun:domain-solver
  labels:
    app: porkbun
    release: porkbun-v0.0.1
    heritage: porkbun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: porkbun:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cert-manager
  name: porkbun:secret-reader
  labels:
    app: porkbun
    release: porkbun-v0.0.1
    heritage: porkbun
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porkbun:secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: porkbun:secret-reader
subjects:
- kind: ServiceAccount
  name: porkbun
  namespace: cert-manager
